### ISSUE TITLE
Excellent design!

### ISSUE THREAD

**Issue by ningpj** [geoffrey-young/3D-Printing#1]
Awesome work.  I have long bowden tubes as well and was designing a buffer that could handle 1100mm of filament without needing a wheel and could be loaded quickly.  Your adaptation and design works really well and have shelved my project after testing your cart design this week.  My thanks and gratitude.

The only change I'm planing at this stage is to cut clear acrylic sheet for the buffer ends to limit potential moisture issues and airflow around spooled ABS. Probably wont make a material difference but easy to do.  

Sourcing m2 self tappers with hex or phillips head screws with small heads quickly where I live is proving a little difficult. 
buffer-top-magnet+magnet.stl needs to be printed vertical to avoid supports for clip & slot number.  Initial overhang is > 45 degrees on rounded radius and would be easier to print if it was a constant 45 for this particular part.  

Regards

**Comment by ningpj** [comment]
Disregard comment re vertical orientation...now printing buffer-top_magnet+magnet.stl on side with minimum supports required.  was concerned about number slot and being difficult to side the number in if supports were used but came off cleaner than expected.

**Comment by geoffrey-young** [comment]
glad you found it useful :)

I've updated the models so they're all already in the proper orientation, and added some printing notes as well.
